-- MySQL Script generated by MySQL Workbench
-- 08/28/14 23:32:17
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema Books
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Books` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `Books` ;

-- -----------------------------------------------------
-- Table `Books`.`Author`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Books`.`Author` (
  `idAuthor` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) NULL,
  PRIMARY KEY (`idAuthor`),
  UNIQUE INDEX `idAuthor_UNIQUE` (`idAuthor` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Books`.`Book`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Books`.`Book` (
  `idBook` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) NULL,
  `date` DATETIME NULL,
  `ISBN` VARCHAR(45) NULL,
  `AuthorID` INT NOT NULL,
  PRIMARY KEY (`idBook`, `AuthorID`),
  UNIQUE INDEX `idBook_UNIQUE` (`idBook` ASC),
  INDEX `fk_Book_Author_idx` (`AuthorID` ASC),
  CONSTRAINT `fk_Book_Author`
    FOREIGN KEY (`AuthorID`)
    REFERENCES `Books`.`Author` (`idAuthor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
