//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _05.StringChecker.Client.StringCheckerService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="StringCheckerService.IStringCheckerSvc")]
    public interface IStringCheckerSvc {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStringCheckerSvc/CheckStrings", ReplyAction="http://tempuri.org/IStringCheckerSvc/CheckStringsResponse")]
        int CheckStrings(string first, string second);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStringCheckerSvc/CheckStrings", ReplyAction="http://tempuri.org/IStringCheckerSvc/CheckStringsResponse")]
        System.Threading.Tasks.Task<int> CheckStringsAsync(string first, string second);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IStringCheckerSvcChannel : _05.StringChecker.Client.StringCheckerService.IStringCheckerSvc, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class StringCheckerSvcClient : System.ServiceModel.ClientBase<_05.StringChecker.Client.StringCheckerService.IStringCheckerSvc>, _05.StringChecker.Client.StringCheckerService.IStringCheckerSvc {
        
        public StringCheckerSvcClient() {
        }
        
        public StringCheckerSvcClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public StringCheckerSvcClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StringCheckerSvcClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StringCheckerSvcClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int CheckStrings(string first, string second) {
            return base.Channel.CheckStrings(first, second);
        }
        
        public System.Threading.Tasks.Task<int> CheckStringsAsync(string first, string second) {
            return base.Channel.CheckStringsAsync(first, second);
        }
    }
}
