//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _02.DateTimeService.Client.DayOfWeekService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="DayOfWeekService.IDayOfWeekService")]
    public interface IDayOfWeekService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDayOfWeekService/GetDayOfWeekFromDateTime", ReplyAction="http://tempuri.org/IDayOfWeekService/GetDayOfWeekFromDateTimeResponse")]
        string GetDayOfWeekFromDateTime(System.DateTime date);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDayOfWeekService/GetDayOfWeekFromDateTime", ReplyAction="http://tempuri.org/IDayOfWeekService/GetDayOfWeekFromDateTimeResponse")]
        System.Threading.Tasks.Task<string> GetDayOfWeekFromDateTimeAsync(System.DateTime date);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDayOfWeekService/GetDayOfWeekFromString", ReplyAction="http://tempuri.org/IDayOfWeekService/GetDayOfWeekFromStringResponse")]
        string GetDayOfWeekFromString(string date);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDayOfWeekService/GetDayOfWeekFromString", ReplyAction="http://tempuri.org/IDayOfWeekService/GetDayOfWeekFromStringResponse")]
        System.Threading.Tasks.Task<string> GetDayOfWeekFromStringAsync(string date);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IDayOfWeekServiceChannel : _02.DateTimeService.Client.DayOfWeekService.IDayOfWeekService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DayOfWeekServiceClient : System.ServiceModel.ClientBase<_02.DateTimeService.Client.DayOfWeekService.IDayOfWeekService>, _02.DateTimeService.Client.DayOfWeekService.IDayOfWeekService {
        
        public DayOfWeekServiceClient() {
        }
        
        public DayOfWeekServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DayOfWeekServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DayOfWeekServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DayOfWeekServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetDayOfWeekFromDateTime(System.DateTime date) {
            return base.Channel.GetDayOfWeekFromDateTime(date);
        }
        
        public System.Threading.Tasks.Task<string> GetDayOfWeekFromDateTimeAsync(System.DateTime date) {
            return base.Channel.GetDayOfWeekFromDateTimeAsync(date);
        }
        
        public string GetDayOfWeekFromString(string date) {
            return base.Channel.GetDayOfWeekFromString(date);
        }
        
        public System.Threading.Tasks.Task<string> GetDayOfWeekFromStringAsync(string date) {
            return base.Channel.GetDayOfWeekFromStringAsync(date);
        }
    }
}
