-- MySQL Script generated by MySQL Workbench
-- 08/22/14 02:08:26
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Faculty`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Faculty` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Faculty` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `ID_UNIQUE` ON `mydb`.`Faculty` (`ID` ASC);


-- -----------------------------------------------------
-- Table `mydb`.`Department`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Department` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Department` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) NULL,
  `Faculty_ID` INT NOT NULL,
  PRIMARY KEY (`ID`),
  CONSTRAINT `fk_Department_Faculty`
    FOREIGN KEY (`Faculty_ID`)
    REFERENCES `mydb`.`Faculty` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE UNIQUE INDEX `ID_UNIQUE` ON `mydb`.`Department` (`ID` ASC);

CREATE INDEX `fk_Department_Faculty_idx` ON `mydb`.`Department` (`Faculty_ID` ASC);


-- -----------------------------------------------------
-- Table `mydb`.`Professor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Professor` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Professor` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Department_ID` INT NOT NULL,
  PRIMARY KEY (`ID`),
  CONSTRAINT `fk_Professor_Department1`
    FOREIGN KEY (`Department_ID`)
    REFERENCES `mydb`.`Department` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Professor_Department1_idx` ON `mydb`.`Professor` (`Department_ID` ASC);


-- -----------------------------------------------------
-- Table `mydb`.`Course`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Course` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Course` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) NULL,
  `Department_ID` INT NOT NULL,
  `Professor_ID` INT NOT NULL,
  PRIMARY KEY (`ID`),
  CONSTRAINT `fk_Course_Department1`
    FOREIGN KEY (`Department_ID`)
    REFERENCES `mydb`.`Department` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Course_Professor1`
    FOREIGN KEY (`Professor_ID`)
    REFERENCES `mydb`.`Professor` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Course_Department1_idx` ON `mydb`.`Course` (`Department_ID` ASC);

CREATE INDEX `fk_Course_Professor1_idx` ON `mydb`.`Course` (`Professor_ID` ASC);

CREATE UNIQUE INDEX `ID_UNIQUE` ON `mydb`.`Course` (`ID` ASC);


-- -----------------------------------------------------
-- Table `mydb`.`Titles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Titles` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Titles` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Title_Name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `ID_UNIQUE` ON `mydb`.`Titles` (`ID` ASC);

CREATE UNIQUE INDEX `Title_Name_UNIQUE` ON `mydb`.`Titles` (`Title_Name` ASC);


-- -----------------------------------------------------
-- Table `mydb`.`Professor_has_Titles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Professor_has_Titles` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Professor_has_Titles` (
  `Professor_ID` INT NOT NULL,
  `Titles_ID` INT NOT NULL,
  PRIMARY KEY (`Professor_ID`, `Titles_ID`),
  CONSTRAINT `fk_Professor_has_Titles_Professor1`
    FOREIGN KEY (`Professor_ID`)
    REFERENCES `mydb`.`Professor` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Professor_has_Titles_Titles1`
    FOREIGN KEY (`Titles_ID`)
    REFERENCES `mydb`.`Titles` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Professor_has_Titles_Titles1_idx` ON `mydb`.`Professor_has_Titles` (`Titles_ID` ASC);

CREATE INDEX `fk_Professor_has_Titles_Professor1_idx` ON `mydb`.`Professor_has_Titles` (`Professor_ID` ASC);


-- -----------------------------------------------------
-- Table `mydb`.`Student`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Student` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Student` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `ID_UNIQUE` ON `mydb`.`Student` (`ID` ASC);


-- -----------------------------------------------------
-- Table `mydb`.`Course_has_Student`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Course_has_Student` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Course_has_Student` (
  `Course_ID` INT NOT NULL,
  `Student_ID` INT NOT NULL,
  PRIMARY KEY (`Course_ID`, `Student_ID`),
  CONSTRAINT `fk_Course_has_Student_Course1`
    FOREIGN KEY (`Course_ID`)
    REFERENCES `mydb`.`Course` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Course_has_Student_Student1`
    FOREIGN KEY (`Student_ID`)
    REFERENCES `mydb`.`Student` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Course_has_Student_Student1_idx` ON `mydb`.`Course_has_Student` (`Student_ID` ASC);

CREATE INDEX `fk_Course_has_Student_Course1_idx` ON `mydb`.`Course_has_Student` (`Course_ID` ASC);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
